// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DIRECT_URL for CLI tasks (migrate/introspect) and use DATABASE_URL as fallback.
    // For Cloud SQL, DIRECT_URL can point to a direct/private endpoint while DATABASE_URL
    // can stay aligned with runtime networking policy.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
